[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"
ar = "i686-w64-mingw32-ar"

[target.i686-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "target-feature=+crt-static"]

# Linux targets for completeness
[target.x86_64-unknown-linux-gnu]
linker = "gcc"

[target.i686-unknown-linux-gnu]
linker = "gcc"